#!/bin/bash
#g++ -o testAthlet -I /usr/share/qt3/include -I../ -I /usr/include/kde -lqt-mt -lkdeui -Wall testAthlet.cpp ../Athlet.cpp ../AthletParser.cpp
 
g++ -o testRun -I /usr/share/qt3/include -I../ -I /usr/include/kde -lqt-mt -lkdeui -Wall testRun.cpp ../Run.cpp ../RunParser.cpp
